# -*- coding: utf-8 -*-
"""triangle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1st2AEqXMUS_1yRYAx3wb2WqGPocvk0ac
"""

import matplotlib.pyplot as plt

# AB
x1 = [4,1]
y1 = [3,-3]
# plotting  
plt.plot(x1, y1,color='blue')
# BC
x2 = [1,-3]
y2 = [-3,1]
# plotting  
plt.plot(x2, y2,color='red')
# AC
x1 = [4,-3]
y1 = [3,1]
# plotting 
plt.plot(x1, y1,color='green')

plt.annotate("A,P", (4, 3))
plt.annotate("B,R", (1, -3))
plt.annotate("C,Q", (-3, 1))


plt.ylabel('$y-axis$')
plt.xlabel('$x-axis$')
plt.grid() 
plt.axis('equal')
plt.show()